import { Actor, ActorSubclass, HttpAgent } from "@dfinity/agent";
import type { Identity } from "@dfinity/agent";
import type { IDL } from "@dfinity/candid";
import {
  idlFactory as daoBackendIdl,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - _SERVICE is generated by dfx at build time
  _SERVICE as DaoBackendService
} from "@declarations/dao_backend/dao_backend.did.js";
import type { Activity } from "@declarations/dao_backend/dao_backend.did";

type DaoBackendServiceExtended = DaoBackendService & {
  getRecentActivity: () => Promise<Activity[]>;
};
import {
  idlFactory as governanceIdl,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - _SERVICE is generated by dfx at build time
  _SERVICE as GovernanceService
} from "@declarations/governance/governance.did.js";
import {
  idlFactory as proposalsIdl,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - _SERVICE is generated by dfx at build time
  _SERVICE as ProposalsService
} from "@declarations/proposals/proposals.did.js";
import {
  idlFactory as stakingIdl,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - _SERVICE is generated by dfx at build time
  _SERVICE as StakingService
} from "@declarations/staking/staking.did.js";
import {
  idlFactory as treasuryIdl,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - _SERVICE is generated by dfx at build time
  _SERVICE as TreasuryService
} from "@declarations/treasury/treasury.did.js";
import {
  idlFactory as assetsIdl,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - _SERVICE is generated by dfx at build time
  _SERVICE as AssetsService,
} from "@declarations/assets/assets.did.js";

declare global {
  interface Window {
    global: typeof globalThis;
  }
}

// Ensure global is defined in the browser context
if (typeof window !== "undefined") {
  window.global = window;
}

export interface CanisterIds {
  daoBackend: string;
  governance?: string;
  staking?: string;
  treasury?: string;
  proposals?: string;
  assets?: string;
}

const createActor = async <T>(
  canisterId: string,
  idlFactory: IDL.InterfaceFactory,
  identity?: Identity
): Promise<ActorSubclass<T>> => {
  try {
    console.log("Creating actor for canister ID:", canisterId);
    
    // Check if canisterId is valid
    if (!canisterId || canisterId === 'undefined' || canisterId.includes('_')) {
      throw new Error(`Invalid canister ID: ${canisterId}`);
    }

    // Determine the correct host based on the environment
    let host = import.meta.env.VITE_HOST;
    
    // If we're in a canister environment, use the current window location
    if (typeof window !== 'undefined' && window.location.hostname.includes('.localhost')) {
      host = `${window.location.protocol}//${window.location.hostname}:${window.location.port}`;
    } else if (!host) {
      host = "http://127.0.0.1:4943";
    }

    console.log("Using host:", host);

    const agent = new HttpAgent({
      host: host,
      verifyQuerySignatures: false,
      identity,
    });

    if (identity) {
      const principal = await agent.getPrincipal();
      console.log("HttpAgent principal:", principal.toString());
    }

    // Only fetch the root key when we're in development
    if (import.meta.env.VITE_DFX_NETWORK !== "ic") {
      await agent.fetchRootKey().catch(err => {
        console.warn("Unable to fetch root key. Check to ensure that your local replica is running");
        console.error(err);
      });
    }

    return Actor.createActor<T>(idlFactory, {
      agent,
      canisterId,
    });
  } catch (error) {
    console.error("Error creating actor:", error);
    throw error;
  }
};

export interface Actors {
  daoBackend: ActorSubclass<DaoBackendServiceExtended>;
  governance: ActorSubclass<GovernanceService>;
  staking: ActorSubclass<StakingService>;
  treasury: ActorSubclass<TreasuryService>;
  proposals: ActorSubclass<ProposalsService>;
  assets: ActorSubclass<AssetsService>;
}

const createMockActor = <T>(): ActorSubclass<T> => {
  return new Proxy({} as ActorSubclass<T>, {
    get: (target, prop) => {
      if (typeof prop === 'string') {
        return async (...args: any[]) => {
          console.warn(`Mock actor method called: ${prop}`, args);
          if (prop.includes('get') || prop.includes('fetch') || prop.includes('list')) {
            return null;
          }
          return { ok: true } as unknown as T;
        };
      }
      return target[prop as keyof ActorSubclass<T>];
    }
  });
};

const handleOptionalActor = async <T>(
  canisterId: string | undefined,
  idl: IDL.InterfaceFactory,
  name: string,
  identity?: Identity
): Promise<ActorSubclass<T>> => {
  if (!canisterId) {
    if (import.meta.env.DEV) {
      return createMockActor<T>();
    }
    throw new Error(`Missing canister ID for ${name}`);
  }
  try {
    return await createActor<T>(canisterId, idl, identity);
  } catch (error) {
    if (import.meta.env.DEV) {
      console.warn(`Failed to create ${name.toLowerCase()} actor, using mock:`, error);
      return createMockActor<T>();
    }
    throw error;
  }
};

export const initializeAgents = async (
  canisterIds: CanisterIds,
  daoId: string,
  identity?: Identity
): Promise<Actors> => {
  try {
    const daoBackend = await createActor<DaoBackendServiceExtended>(
      canisterIds.daoBackend,
      daoBackendIdl,
      identity
    );

    const assets = await handleOptionalActor<AssetsService>(
      canisterIds.assets,
      assetsIdl,
      "ASSETS",
      identity
    );

    let governanceCanisterId: string | undefined = canisterIds.governance;

    if (!governanceCanisterId) {
      try {
        const references = await daoBackend.getCanisterReferences(daoId);
        const principal = references.governance[0];
        if (!principal) {
          throw new Error("Governance canister principal not found");
        }
        governanceCanisterId = principal.toString();
      } catch (err) {
        console.error("Failed to retrieve governance canister ID:", err);
        throw new Error("Unable to retrieve governance canister principal");
      }
    }

    const governance = await handleOptionalActor<GovernanceService>(
      governanceCanisterId,
      governanceIdl,
      "GOVERNANCE",
      identity
    );

    const staking = await handleOptionalActor<StakingService>(
      canisterIds.staking,
      stakingIdl,
      "STAKING",
      identity
    );

    const treasury = await handleOptionalActor<TreasuryService>(
      canisterIds.treasury,
      treasuryIdl,
      "TREASURY",
      identity
    );

    const proposals = await handleOptionalActor<ProposalsService>(
      canisterIds.proposals,
      proposalsIdl,
      "PROPOSALS",
      identity
    );

    return {
      daoBackend,
      governance,
      staking,
      treasury,
      proposals,
      assets,
    };
  } catch (error) {
    console.error("Failed to initialize agents:", error);
    throw error;
  }
};
